[ALPS01812771] cpu: fix cpu_uevent not used build warning
Commit 9025d688a3bcd3 ("cpu: add generic support for CPU feature
based module autoloading") introduce the following build warning.

drivers/base/cpu.c:317:12: error: cpu_uevent defined but not used [-Werror=unused-function]

Align upstream 67bad2fdb754dbe ("cpu: add generic support for CPU
feature based module autoloading") to fix this issue.

MTK-Commit-Id: 7b461ab3ac32d45b5f954d0046ca75b16823bcf8

Change-Id: Ied34f92d63729df766bc10e9e2aae210e22331fc
Signed-off-by: Shangbing Hu <shangbing.hu@mediatek.com>
CR-Id: ALPS01812771
Feature: cpu