[ALPS02306348] display driver: support 32bit kernel
[Detail] undefined reference to __aeabi_uldivmod

[Solution] use do_div instead of /

[Feature] null

MTK-Commit-Id: 11b27b38ffb6c00d8c453d18e403bd54fe615069

Change-Id: I8bfda8ce5b0a331d08e2e321f0fd21c0b35edff8
Signed-off-by: Shangbing Hu <shangbing.hu@mediatek.com>
CR-Id: ALPS02306348