[ALPS02744402] mm: slub: fix format mismatches in slab_err() callers
[Detail]
Adding __printf(3, 4) to slab_err exposed following:
mm/slub.c: In function `check_slab:
mm/slub.c:852:4: warning: format `%u expects argument of type `unsigned int, but argument 4 has type `const char * [-Wformat=]
s->name, page->objects, maxobj);
^
mm/slub.c:852:4: warning: too many arguments for format [-Wformat-extra-args]
mm/slub.c:857:4: warning: format `%u expects argument of type `unsigned int, but argument 4 has type `const char * [-Wformat=]
s->name, page->inuse, page->objects);
^
mm/slub.c:857:4: warning: too many arguments for format [-Wformat-extra-args]

mm/slub.c: In function `on_freelist:
mm/slub.c:905:4: warning: format `%d expects argument of type `int, but argument 5 has type `long unsigned int [-Wformat=]
"should be %d", page->objects, max_objects);

[Solution]
Fix first two warnings by removing redundant s->name.
Fix the last by changing type of max_object from unsigned long to int.

MTK-Commit-Id: 33d88c1bcee8579130bfa929b287f46e5883e25c

Change-Id: Ib0919173e27f65aa1a8328c187f18e7d4f64ef66
Signed-off-by: Andrey Ryabinin <a.ryabinin@samsung.com>
Cc: Christoph Lameter <cl@linux.com>
Cc: Pekka Enberg <penberg@kernel.org>
Acked-by: David Rientjes <rientjes@google.com>
Cc: Joonsoo Kim <iamjoonsoo.kim@lge.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>
CR-Id: ALPS02744402
Feature: MTBF(*)
(cherry picked from commit 1a49d3a4c072cbf1b95b01c7d2387970b758d72d)