[ALPS02252420] GPU_DVFS: remove unused header file
[Detail] fatal error: mt-plat/mt_typedefs.h: No such file
so no need to include this file at kenel-3.18,
error: unused variable cur_vcore.

[Solution] remove mt-plat/mt_typedefs.h, add macro
 STATIC_PWR_READY2USE to prevent build error.

[Feature] GPU DVFS

	drivers/misc/mediatek/base/power/mt6797/mt_gpufreq.c

[Detail]

[Solution]

[Feature] GPU DVFS

MTK-Commit-Id: a77cef8b61fcd71d2ab3d1223f0a6c1427b437d5

Change-Id: I8c4003ebce3cf971e2085b9fc4b4c1dec70d2e62
Signed-off-by: Shangbing Hu <shangbing.hu@mediatek.com>
Conflicts:
CR-Id: ALPS02252420