[ALPS02787948] sdcardfs: fix case insensitive lookup in lower dir.
[Detail]
When sdcardfs is enabled, CTS test (NRD88) is failed at
android.provider.cts.MediaStore_FilesTest#testCaseSensitivity.

  testCaseSensitivity(android.provider.cts.MediaStore_FilesTest)
  java.io.FileNotFoundException: No such file or directory

The problem also can be reproduced by following adb commands:
  adb shell "echo 123 > /storage/emulated/0/test/Test.Mp3"
  adb shell "echo 3 > /proc/sys/vm/drop_caches"
  adb shell "ls /storage/emulated/0/test/test.mp3"
  => ls: /storage/emulated/0/test/test.mp3: No such file or directory

__sdcardfs_lookup() uses vfs_path_lookup() to check if the dentry
exists or not. vfs_path_lookup() will call down to the .lookup() of
the lower file system. Since ext4_lookup() is case sensitive, and
the lower path cannot be found.

[Solution]
If the dentry was not found in vfs_path_lookup(), and the intent
is not create or rename file. Try case insensitive search in lower
parent directory, and then call vfs_path_lookup() again to get path
to alias dentry.

MTK-Commit-Id: 37a58f5aca7f48ed04c4336f72670b492eea261a

Change-Id: I4cd4cd4de6c42b695c37a9bfb436d1b54b733fb5
Signed-off-by: Shangbing Hu <shangbing.hu@mediatek.com>
CR-Id: ALPS02787948
Feature: CTS(*)