[ALPS02800959] battery: Rename PEP_ICHG_LEAVE_THRESHOLD
[Detail]
Since PEP_ICHG_LEAVE_THRESHOLD may not defind in other platform.
Change it too 1000 mA by default to avoid build break.

drivers/power/mediatek/mtk_pep_intf.c:150:29:
error: PEP_ICHG_LEAVE_THRESHOLD undeclared

MTK-Commit-Id: 2420f8e9bbd53fb9275a97b5ff512e6713f2157b

Change-Id: I0677a066e91bf2d7f617b46a7b1ad49aceb791de
Signed-off-by: Shangbing Hu <shangbing.hu@mediatek.com>
CR-Id: ALPS02800959
Feature: pump express charging. (fast charging)