[ALPS02438843] fuelgauge: fixed compile error
[Detail]
Compile error in K55V1_64_OM_6M_BRM
error: unused variable temp_strptr

[Solution]
temp_strptr is used in CONFIG_MTK_KERNEL_POWER_OFF_CHARGING.
So add ifdef when claim temp_strptr

MTK-Commit-Id: 384f9785b1e967d338e2b746fa00d9bb8d1f4dcd

Change-Id: I197c0b0d6bc7aaca20f7b4a16ee5479a1a5aaa69
Signed-off-by: Shangbing Hu <shangbing.hu@mediatek.com>
CR-Id: ALPS02438843
Feature: Fuel Gauge