[ALPS02363965] Build error: fix build error
[Detail]
Daily build error, implicit declaration of function

[Solution]
use correct function, fix it

[Feature]
Denali2 single panel feature

MTK-Commit-Id: 7da012273a705955514fa0a38ba41953cce06c6a

Change-Id: I9cd0200696c44005b425bc3bf6e5642742c2c0eb
CR-Id:ALPS02363965
Signed-off-by: Shangbing Hu <shangbing.hu@mediatek.com>
(cherry picked from commit 2f6289bda00581349713a9c151118dbd22bb0cbd)
(cherry picked from commit db55444e75e53ecc342f8bc74c9ce89e4e4f384a)