[ALPS02135081] SPM: fix MT6753 build error in mt_spm.c
[Detail]
Fix MT6753 build error in mt_spm.c because is_ext_buck_exist() is not ready

[Solution]
Fix the following build errors:

drivers/built-in.o: In function `__spm_enable_i2c4_clk:
/alps/DailyBuild/CodeBase/alps/kernel-3.18/drivers/misc/mediatek/base/power/mt6735/mt_spm_internal.c:425: undefined reference to `is_ext_buck_exist
drivers/built-in.o: In function `__spm_disable_i2c4_clk:
/alps/DailyBuild/CodeBase/alps/kernel-3.18/drivers/misc/mediatek/base/power/mt6735/mt_spm_internal.c:438: undefined reference to `is_ext_buck_exist

[Feature] Power Management

MTK-Commit-Id: 252006befa25e9ff3a5f0943468b2cd372c9b0c2

Change-Id: I826ad5d327df2f2980ce81640b67d823c196d48c
Signed-off-by: Shangbing Hu <shangbing.hu@mediatek.com>
CR-Id: ALPS02135081