[ALPS02353186] usb : fix coverity error
[Detail]
    [Coverity Scanned Code Defect] 67662: Copy-paste error
copy_paste_error: ep_mult in k <= ep_mult looks like a copy-paste error

[Solution]
    cur_ep_offset = ep_offset + (k * ep_mult);
ep_repeat instead of ep_mult

MTK-Commit-Id: fe401dae8f4092f476b86929e2095bd66713e588

Change-Id: Iab92386b3cd80ad5f3b87c0026a71925ff209fa8
Signed-off-by: Shangbing Hu <shangbing.hu@mediatek.com>
CR-Id: ALPS02353186
Feature: Others